### PR TITLE
extended the run time for slow rule in annotate

### LINKED ISSUE #77: Annotation (`annotate_annotate_CAZI_split`) Timeouts
Some fraction of jobs seem to run into a timeout at the `annotate_annotate_CAZI_split` step and get killed by the LSF scheduler. 

Solution - have snakemake increase the time for these jobs. ([for example](https://github.mskcc.org/Microbiome/isabl_microbiome_apps/blob/237493f19fe4f463c0a90caf5cfd59d0019e1805/isabl_microbiome_apps/apps/shotgun/biobakery.py#L286))

### PR DESCRIPTION
**Pull request by miraep8**
Fixes #77 

Alright, I will admit I got a bit turned around by where the best place to put this was (ie in the isabl apps repo vs here).  I think here makes the most sense to me though.   Here is my plan to update isabl:

- merge this small change here
- then update the annotation isabl app to point to the commit associated with this PR but don't update the app version or anything like that. (after all output shouldn't change).

Let me know if this plan will cause any issues with isabl etc!

Cheers

Mirae

### CODE REVIEW

**Comment by nickp60** [comment]
I think this is good! Do you have a rough estimate for the number of jobs that are timing out?  I am a little concerned about bumping the default time to 7 hours just cause we will be penalized on the job priority side of things

**Comment by nickp60** [comment]
An alternative way of approaching this would be to make `nseqs` not hardcoded to 200.  That seemed to work for me by balancing the number of jobs with runtime and I never gave it further though but it could be good to either (a) decrease it across the board, (b) set it based on actual contig length, rather than just the count of sequences.

If we don't want to go that route, I think it could be good to make this use the `retries` variable to bump the runtime if the initial 90min job fails. has been sufficient up til now, so it might be good to keep the 90min default so the jobs get scheduled more readily

**Comment by miraep8** [comment]
Great point! With the current isabl app only 4/54 jobs I submitted succeeded!  (Can check it out if you want - Project 19). The `dbcan` jobs I have been running more recently were taking ~3.5 hours each (but this is not apples to apples comparison - I was requesting more resources per job, but also running a more intensive version of the `db_can` command to predict substrates and group the Cazymes in addition to just annotating the genes, so it is anticipated that it takes a bit longer). Perhaps for this command we could try bumping it up to 3 for now (twice as long as before) and then with the new annotate version I am working on we could request more time if needed for the additional complexity?

**Comment by nickp60** [comment]
Gotcha.  Isabl says that 114/628 Annotate jobs have failed overall so its definitely not limited to your current dataset.

**Comment by miraep8** [comment]
I am also happy to try modifying the `retries` variable first though!  Will make that change here in a bit!    We can then retry it on Project 19s experiments and see if they can make it through.  Interestingly it seems like the current global failure rate of the annotation jobs in isabl is actually ~ 20% (116/628).  Admittedly about 1/2 that is me haha, but the other 1/2 you ran on project 7 seems like it is running into similar issues as I did here! 

I guess this whole discussion makes me wonder:
- I am curious how often the longer job time request actually slows down job fulfillment!  Could test this out it might be nice info to have.  For example I often don't seem to have huge issues getting the `biobakery` jobs provisioned even though they ask for a lot of time.  But this is just anecdotal.  I guess what might be nice is to profile various jobs and see how long they take based on input file size etc, and then dynamically set some of these variables. But for a futre PR I think

**Comment by nickp60** [comment]
If its just a slow tool, I think I'd prefer to do more splitting rather than increasing the runtime.  Would you mind doing a quick 1-sample benchmark to find out if its roughly linear with number of cores used, by running the same job increasing the number of cores?  Its currently using 2 per chunk. My guess is that we might be in better shape if we have short-running jobs, so that could either be by increasing the number of threads or decreasing the input size

**Comment by miraep8** [comment]
Ok 👍

**Comment by nickp60** [comment]
Sure, that sounds good!  If we notice job priority being a problem we can address this then

**Comment by nickp60** [comment]
we might be totally fine with longer runtime requests since the jobs are don't require a ton of other resources

**Comment by miraep8** [comment]
Ok 👍   Yea thinking about it for a second it might eb a bit tricky to split this up actually.  Could be done, but might take me more time than I want to figure out how.  For now will try just bumping time up to 2 hours (from 1.5) and modifying the retries variable. Then as you say go from there :)

**Comment by miraep8** [comment]
Oh ok haha, I guess in that case.... shall we merge it for now then?

**Comment by nickp60** [comment]
Since your runs are taking ~3.5 hours feel free to set that as the default, and then double (or triple) on retries.

**Comment by nickp60** [comment]
Yes -- I'm approving  but would you mind re-running pesky snakefmt before merging?

**Review by nickp60 — APPROVED** [review]

**Pull request merged**
