### PR TITLE
Change submodule validates

### PR DESCRIPTION
**Pull request by miraep8**
I have been reusing parts from the `vdblab-shotgun` in my new snakemake pipeline using the module import capacity.  Unfortunately one downside of having the validate calls in the individual .smk files is that it enforces all the requirements of the `config.schema.yaml` file from `vdblab-shotgun` onto whatever snakefile is trying to use it!  By removing these valideas and setting skip_validate to True (thanks Nick!) I am able to get around these requirements. 

Personally I really like that these are very modular components, I think that this requirement for validation within these sub components makes them less reusable.  Open to another way to solve this problem as well, for now just putting this here as a means to start the conversation. 

Cheers!

### CODE REVIEW

**Comment by miraep8** [comment]
Whoops!  The lint tests are keeping me honest.

**Comment by nickp60** [comment]
Sorry about all the snakefmt issues -- those are all my fault!

**Comment by nickp60** [comment]
Looks good to me! Thanks for doing this.

**Review by nickp60 — APPROVED** [review]
sorry, realize I never approved this!

**Comment by miraep8** [comment]
Alright, cheers - will merge for now then.  Happy to return to this at a future point if it makes sense though regarding larger design choices about how to control modularity with this pipeline.

**Pull request merged**
